import { IPlayer } from "@models/player";

export const PlayerData: IPlayer[] = [
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Patrick Mahomes II",
    adp: 15,
    position: "QB",
    totalPoints: 415.8,
    pointsPerGame: 24.5,
    gamesPlayed: 17,
    completions: 435,
    passYards: 5250,
    passTds: 41,
    interceptions: 12,
    rushAttempts: 61,
    rushYards: 358,
    rushTds: 4,
    targets: 1,
    receptions: 1,
    recYards: 6,
    recTds: 0,
    fumbles: 0,
    teamName: "KC",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Josh Allen",
    adp: 22,
    position: "QB",
    totalPoints: 395.5,
    pointsPerGame: 24.7,
    gamesPlayed: 16,
    completions: 359,
    passYards: 4283,
    passTds: 35,
    interceptions: 14,
    rushAttempts: 124,
    rushYards: 762,
    rushTds: 7,
    targets: 0,
    receptions: 0,
    recYards: 0,
    recTds: 0,
    fumbles: 5,
    teamName: "BUF",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Jalen Hurts",
    adp: 24,
    position: "QB",
    totalPoints: 378,
    pointsPerGame: 25.2,
    gamesPlayed: 15,
    completions: 306,
    passYards: 3701,
    passTds: 22,
    interceptions: 6,
    rushAttempts: 165,
    rushYards: 760,
    rushTds: 13,
    targets: 0,
    receptions: 0,
    recYards: 0,
    recTds: 0,
    fumbles: 2,
    teamName: "PHI",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Austin Ekeler",
    adp: 3,
    position: "RB",
    totalPoints: 372.7,
    pointsPerGame: 21.9,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 204,
    rushYards: 915,
    rushTds: 13,
    targets: 128,
    receptions: 107,
    recYards: 722,
    recTds: 5,
    fumbles: 3,
    teamName: "LAC",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Justin Jefferson",
    adp: 1,
    position: "WR",
    totalPoints: 367.3,
    pointsPerGame: 21.6,
    gamesPlayed: 17,
    completions: 2,
    passYards: 34,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 4,
    rushYards: 24,
    rushTds: 1,
    targets: 184,
    receptions: 128,
    recYards: 1809,
    recTds: 8,
    fumbles: 0,
    teamName: "MIN",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Christian McCaffrey",
    adp: 2,
    position: "RB",
    totalPoints: 351,
    pointsPerGame: 20.6,
    gamesPlayed: 17,
    completions: 1,
    passYards: 34,
    passTds: 1,
    interceptions: 0,
    rushAttempts: 244,
    rushYards: 1139,
    rushTds: 8,
    targets: 108,
    receptions: 85,
    recYards: 741,
    recTds: 5,
    fumbles: 0,
    teamName: "SF",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Joe Burrow",
    adp: 37,
    position: "QB",
    totalPoints: 350.7,
    pointsPerGame: 21.9,
    gamesPlayed: 16,
    completions: 414,
    passYards: 4475,
    passTds: 35,
    interceptions: 12,
    rushAttempts: 75,
    rushYards: 257,
    rushTds: 5,
    targets: 0,
    receptions: 0,
    recYards: 0,
    recTds: 0,
    fumbles: 3,
    teamName: "CIN",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Tyreek Hill",
    adp: 7,
    position: "WR",
    totalPoints: 347.2,
    pointsPerGame: 20.4,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 7,
    rushYards: 32,
    rushTds: 2,
    targets: 170,
    receptions: 119,
    recYards: 1710,
    recTds: 7,
    fumbles: 0,
    teamName: "MIA",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Davante Adams",
    adp: 12,
    position: "WR",
    totalPoints: 335.5,
    pointsPerGame: 19.7,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 3,
    rushYards: -1,
    rushTds: 0,
    targets: 180,
    receptions: 100,
    recYards: 1516,
    recTds: 14,
    fumbles: 0,
    teamName: "LV",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Josh Jacobs",
    adp: 18,
    position: "RB",
    totalPoints: 328.3,
    pointsPerGame: 19.3,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 340,
    rushYards: 1653,
    rushTds: 12,
    targets: 65,
    receptions: 53,
    recYards: 400,
    recTds: 0,
    fumbles: 1,
    teamName: "LV",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Stefon Diggs",
    adp: 10,
    position: "WR",
    totalPoints: 316.6,
    pointsPerGame: 19.8,
    gamesPlayed: 16,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 1,
    rushYards: -3,
    rushTds: 0,
    targets: 153,
    receptions: 108,
    recYards: 1429,
    recTds: 11,
    fumbles: 0,
    teamName: "BUF",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Travis Kelce",
    adp: 6,
    position: "TE",
    totalPoints: 316.3,
    pointsPerGame: 18.6,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 2,
    rushYards: 5,
    rushTds: 0,
    targets: 152,
    receptions: 110,
    recYards: 1338,
    recTds: 12,
    fumbles: 1,
    teamName: "KC",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Geno Smith",
    adp: 114,
    position: "QB",
    totalPoints: 303.9,
    pointsPerGame: 17.9,
    gamesPlayed: 17,
    completions: 399,
    passYards: 4282,
    passTds: 30,
    interceptions: 11,
    rushAttempts: 68,
    rushYards: 366,
    rushTds: 1,
    targets: 0,
    receptions: 0,
    recYards: 0,
    recTds: 0,
    fumbles: 4,
    teamName: "SEA",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "CeeDee Lamb",
    adp: 11,
    position: "WR",
    totalPoints: 301.6,
    pointsPerGame: 17.7,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 10,
    rushYards: 47,
    rushTds: 0,
    targets: 156,
    receptions: 107,
    recYards: 1359,
    recTds: 9,
    fumbles: 0,
    teamName: "DAL",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "A.J. Brown",
    adp: 14,
    position: "WR",
    totalPoints: 299.6,
    pointsPerGame: 17.6,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 0,
    rushYards: 0,
    rushTds: 0,
    targets: 146,
    receptions: 88,
    recYards: 1496,
    recTds: 11,
    fumbles: 2,
    teamName: "PHI",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Derrick Henry",
    adp: 16,
    position: "RB",
    totalPoints: 298.6,
    pointsPerGame: 18.7,
    gamesPlayed: 16,
    completions: 2,
    passYards: 4,
    passTds: 1,
    interceptions: 0,
    rushAttempts: 349,
    rushYards: 1538,
    rushTds: 13,
    targets: 41,
    receptions: 33,
    recYards: 398,
    recTds: 0,
    fumbles: 3,
    teamName: "TEN",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Justin Fields",
    adp: 45,
    position: "QB",
    totalPoints: 296,
    pointsPerGame: 19.7,
    gamesPlayed: 15,
    completions: 192,
    passYards: 2242,
    passTds: 17,
    interceptions: 11,
    rushAttempts: 160,
    rushYards: 1143,
    rushTds: 8,
    targets: 0,
    receptions: 0,
    recYards: 0,
    recTds: 0,
    fumbles: 2,
    teamName: "CHI",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Trevor Lawrence",
    adp: 56,
    position: "QB",
    totalPoints: 295.6,
    pointsPerGame: 17.4,
    gamesPlayed: 17,
    completions: 387,
    passYards: 4113,
    passTds: 25,
    interceptions: 8,
    rushAttempts: 62,
    rushYards: 291,
    rushTds: 5,
    targets: 0,
    receptions: 0,
    recYards: 0,
    recTds: 0,
    fumbles: 9,
    teamName: "JAX",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Kirk Cousins",
    adp: 101,
    position: "QB",
    totalPoints: 291.6,
    pointsPerGame: 17.2,
    gamesPlayed: 17,
    completions: 424,
    passYards: 4547,
    passTds: 29,
    interceptions: 14,
    rushAttempts: 31,
    rushYards: 97,
    rushTds: 2,
    targets: 0,
    receptions: 0,
    recYards: 0,
    recTds: 0,
    fumbles: 3,
    teamName: "MIN",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Daniel Jones",
    adp: 112,
    position: "QB",
    totalPoints: 289,
    pointsPerGame: 18.1,
    gamesPlayed: 16,
    completions: 317,
    passYards: 3205,
    passTds: 15,
    interceptions: 5,
    rushAttempts: 120,
    rushYards: 708,
    rushTds: 7,
    targets: 0,
    receptions: 0,
    recYards: 0,
    recTds: 0,
    fumbles: 3,
    teamName: "NYG",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Saquon Barkley",
    adp: 8,
    position: "RB",
    totalPoints: 284,
    pointsPerGame: 17.8,
    gamesPlayed: 16,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 295,
    rushYards: 1312,
    rushTds: 10,
    targets: 76,
    receptions: 57,
    recYards: 338,
    recTds: 0,
    fumbles: 0,
    teamName: "NYG",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Jared Goff",
    adp: 125,
    position: "QB",
    totalPoints: 282.8,
    pointsPerGame: 16.6,
    gamesPlayed: 17,
    completions: 382,
    passYards: 4438,
    passTds: 29,
    interceptions: 7,
    rushAttempts: 29,
    rushYards: 73,
    rushTds: 0,
    targets: 1,
    receptions: 1,
    recYards: 5,
    recTds: 0,
    fumbles: 4,
    teamName: "DET",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Nick Chubb",
    adp: 13,
    position: "RB",
    totalPoints: 281.4,
    pointsPerGame: 16.6,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 302,
    rushYards: 1525,
    rushTds: 12,
    targets: 37,
    receptions: 27,
    recYards: 239,
    recTds: 1,
    fumbles: 1,
    teamName: "CLE",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Justin Herbert",
    adp: 46,
    position: "QB",
    totalPoints: 280.3,
    pointsPerGame: 16.5,
    gamesPlayed: 17,
    completions: 477,
    passYards: 4739,
    passTds: 25,
    interceptions: 10,
    rushAttempts: 54,
    rushYards: 147,
    rushTds: 0,
    targets: 2,
    receptions: 2,
    recYards: -10,
    recTds: 0,
    fumbles: 3,
    teamName: "LAC",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Tom Brady",
    adp: 303,
    position: "QB",
    totalPoints: 271.7,
    pointsPerGame: 16,
    gamesPlayed: 17,
    completions: 490,
    passYards: 4694,
    passTds: 25,
    interceptions: 9,
    rushAttempts: 29,
    rushYards: -1,
    rushTds: 1,
    targets: 1,
    receptions: 0,
    recYards: 0,
    recTds: 0,
    fumbles: 4,
    teamName: "NULL",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Amon-Ra St. Brown",
    adp: 19,
    position: "WR",
    totalPoints: 267.6,
    pointsPerGame: 16.7,
    gamesPlayed: 16,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 9,
    rushYards: 95,
    rushTds: 0,
    targets: 146,
    receptions: 106,
    recYards: 1161,
    recTds: 6,
    fumbles: 0,
    teamName: "DET",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Jaylen Waddle",
    adp: 23,
    position: "WR",
    totalPoints: 259.2,
    pointsPerGame: 15.2,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 3,
    rushYards: 26,
    rushTds: 0,
    targets: 116,
    receptions: 75,
    recYards: 1356,
    recTds: 8,
    fumbles: 1,
    teamName: "MIA",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "DeVonta Smith",
    adp: 27,
    position: "WR",
    totalPoints: 254.6,
    pointsPerGame: 15,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 0,
    rushYards: 0,
    rushTds: 0,
    targets: 136,
    receptions: 95,
    recYards: 1196,
    recTds: 7,
    fumbles: 1,
    teamName: "PHI",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Rhamondre Stevenson",
    adp: 25,
    position: "RB",
    totalPoints: 249.1,
    pointsPerGame: 14.7,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 210,
    rushYards: 1040,
    rushTds: 5,
    targets: 89,
    receptions: 69,
    recYards: 421,
    recTds: 1,
    fumbles: 1,
    teamName: "NE",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Tony Pollard",
    adp: 21,
    position: "RB",
    totalPoints: 248.8,
    pointsPerGame: 15.5,
    gamesPlayed: 16,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 193,
    rushYards: 1007,
    rushTds: 9,
    targets: 55,
    receptions: 39,
    recYards: 371,
    recTds: 3,
    fumbles: 0,
    teamName: "DAL",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Aaron Jones",
    adp: 39,
    position: "RB",
    totalPoints: 248.6,
    pointsPerGame: 14.6,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 213,
    rushYards: 1121,
    rushTds: 2,
    targets: 72,
    receptions: 59,
    recYards: 395,
    recTds: 5,
    fumbles: 3,
    teamName: "GB",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Amari Cooper",
    adp: 41,
    position: "WR",
    totalPoints: 248,
    pointsPerGame: 14.6,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 1,
    rushAttempts: 0,
    rushYards: 0,
    rushTds: 0,
    targets: 132,
    receptions: 78,
    recYards: 1160,
    recTds: 9,
    fumbles: 0,
    teamName: "CLE",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Ja'Marr Chase",
    adp: 4,
    position: "WR",
    totalPoints: 242.4,
    pointsPerGame: 20.2,
    gamesPlayed: 12,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 5,
    rushYards: 8,
    rushTds: 0,
    targets: 134,
    receptions: 87,
    recYards: 1046,
    recTds: 9,
    fumbles: 2,
    teamName: "CIN",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Christian Kirk",
    adp: 75,
    position: "WR",
    totalPoints: 241.9,
    pointsPerGame: 14.2,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 5,
    rushYards: 11,
    rushTds: 0,
    targets: 133,
    receptions: 84,
    recYards: 1108,
    recTds: 8,
    fumbles: 1,
    teamName: "JAX",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Joe Mixon",
    adp: 34,
    position: "RB",
    totalPoints: 239.5,
    pointsPerGame: 17.1,
    gamesPlayed: 14,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 210,
    rushYards: 814,
    rushTds: 7,
    targets: 74,
    receptions: 60,
    recYards: 441,
    recTds: 2,
    fumbles: 0,
    teamName: "CIN",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Aaron Rodgers",
    adp: 99,
    position: "QB",
    totalPoints: 239.2,
    pointsPerGame: 14.1,
    gamesPlayed: 17,
    completions: 350,
    passYards: 3695,
    passTds: 26,
    interceptions: 12,
    rushAttempts: 34,
    rushYards: 94,
    rushTds: 1,
    targets: 0,
    receptions: 0,
    recYards: 0,
    recTds: 0,
    fumbles: 4,
    teamName: "NYJ",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Dalvin Cook",
    adp: 58,
    position: "RB",
    totalPoints: 237.8,
    pointsPerGame: 14,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 264,
    rushYards: 1173,
    rushTds: 8,
    targets: 56,
    receptions: 39,
    recYards: 295,
    recTds: 2,
    fumbles: 4,
    teamName: "NYJ",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Tyler Lockett",
    adp: 71,
    position: "WR",
    totalPoints: 237.3,
    pointsPerGame: 14.8,
    gamesPlayed: 16,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 0,
    rushYards: 0,
    rushTds: 0,
    targets: 117,
    receptions: 84,
    recYards: 1033,
    recTds: 9,
    fumbles: 2,
    teamName: "SEA",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Lamar Jackson",
    adp: 35,
    position: "QB",
    totalPoints: 236.1,
    pointsPerGame: 19.7,
    gamesPlayed: 12,
    completions: 203,
    passYards: 2242,
    passTds: 17,
    interceptions: 7,
    rushAttempts: 112,
    rushYards: 764,
    rushTds: 3,
    targets: 0,
    receptions: 0,
    recYards: 0,
    recTds: 0,
    fumbles: 2,
    teamName: "BAL",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Tua Tagovailoa",
    adp: 87,
    position: "QB",
    totalPoints: 230.9,
    pointsPerGame: 17.8,
    gamesPlayed: 13,
    completions: 259,
    passYards: 3548,
    passTds: 25,
    interceptions: 8,
    rushAttempts: 24,
    rushYards: 70,
    rushTds: 0,
    targets: 0,
    receptions: 0,
    recYards: 0,
    recTds: 0,
    fumbles: 1,
    teamName: "MIA",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Terry McLaurin",
    adp: 50,
    position: "WR",
    totalPoints: 229,
    pointsPerGame: 13.5,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 7,
    rushYards: 29,
    rushTds: 0,
    targets: 120,
    receptions: 77,
    recYards: 1191,
    recTds: 5,
    fumbles: 0,
    teamName: "WAS",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Leonard Fournette",
    adp: 188,
    position: "RB",
    totalPoints: 228.1,
    pointsPerGame: 14.3,
    gamesPlayed: 16,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 1,
    rushAttempts: 189,
    rushYards: 668,
    rushTds: 3,
    targets: 83,
    receptions: 73,
    recYards: 523,
    recTds: 3,
    fumbles: 0,
    teamName: "NULL",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Brandon Aiyuk",
    adp: 72,
    position: "WR",
    totalPoints: 227.8,
    pointsPerGame: 13.4,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 2,
    rushYards: 23,
    rushTds: 0,
    targets: 114,
    receptions: 78,
    recYards: 1015,
    recTds: 8,
    fumbles: 1,
    teamName: "SF",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "DK Metcalf",
    adp: 33,
    position: "WR",
    totalPoints: 226.8,
    pointsPerGame: 13.3,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 0,
    rushYards: 0,
    rushTds: 0,
    targets: 141,
    receptions: 90,
    recYards: 1048,
    recTds: 6,
    fumbles: 2,
    teamName: "SEA",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Jamaal Williams",
    adp: 95,
    position: "RB",
    totalPoints: 225.9,
    pointsPerGame: 13.3,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 262,
    rushYards: 1066,
    rushTds: 17,
    targets: 16,
    receptions: 12,
    recYards: 73,
    recTds: 0,
    fumbles: 2,
    teamName: "NO",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Mike Evans",
    adp: 74,
    position: "WR",
    totalPoints: 225.4,
    pointsPerGame: 15,
    gamesPlayed: 15,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 0,
    rushYards: 0,
    rushTds: 0,
    targets: 128,
    receptions: 77,
    recYards: 1124,
    recTds: 6,
    fumbles: 0,
    teamName: "TB",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Russell Wilson",
    adp: 126,
    position: "QB",
    totalPoints: 224.7,
    pointsPerGame: 15,
    gamesPlayed: 15,
    completions: 292,
    passYards: 3524,
    passTds: 16,
    interceptions: 11,
    rushAttempts: 55,
    rushYards: 277,
    rushTds: 3,
    targets: 1,
    receptions: 1,
    recYards: 1,
    recTds: 0,
    fumbles: 2,
    teamName: "DEN",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Najee Harris",
    adp: 28,
    position: "RB",
    totalPoints: 223.7,
    pointsPerGame: 13.2,
    gamesPlayed: 17,
    completions: 1,
    passYards: 4,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 272,
    rushYards: 1038,
    rushTds: 7,
    targets: 53,
    receptions: 41,
    recYards: 229,
    recTds: 3,
    fumbles: 2,
    teamName: "PIT",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Chris Godwin",
    adp: 66,
    position: "WR",
    totalPoints: 222.8,
    pointsPerGame: 14.9,
    gamesPlayed: 15,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 3,
    rushYards: 5,
    rushTds: 0,
    targets: 142,
    receptions: 104,
    recYards: 1023,
    recTds: 3,
    fumbles: 2,
    teamName: "TB",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Tee Higgins",
    adp: 29,
    position: "WR",
    totalPoints: 220.9,
    pointsPerGame: 13.8,
    gamesPlayed: 16,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 0,
    rushYards: 0,
    rushTds: 0,
    targets: 110,
    receptions: 74,
    recYards: 1029,
    recTds: 7,
    fumbles: 0,
    teamName: "CIN",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Derek Carr",
    adp: 161,
    position: "QB",
    totalPoints: 219.1,
    pointsPerGame: 14.6,
    gamesPlayed: 15,
    completions: 305,
    passYards: 3522,
    passTds: 24,
    interceptions: 14,
    rushAttempts: 24,
    rushYards: 102,
    rushTds: 0,
    targets: 0,
    receptions: 0,
    recYards: 0,
    recTds: 0,
    fumbles: 0,
    teamName: "NO",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Miles Sanders",
    adp: 47,
    position: "RB",
    totalPoints: 216.7,
    pointsPerGame: 12.7,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 259,
    rushYards: 1269,
    rushTds: 11,
    targets: 26,
    receptions: 20,
    recYards: 78,
    recTds: 0,
    fumbles: 2,
    teamName: "CAR",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Michael Pittman Jr.",
    adp: 79,
    position: "WR",
    totalPoints: 216.5,
    pointsPerGame: 13.5,
    gamesPlayed: 16,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 3,
    rushYards: 30,
    rushTds: 0,
    targets: 141,
    receptions: 99,
    recYards: 925,
    recTds: 4,
    fumbles: 1,
    teamName: "IND",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Garrett Wilson",
    adp: 20,
    position: "WR",
    totalPoints: 215.7,
    pointsPerGame: 12.7,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 4,
    rushYards: 4,
    rushTds: 0,
    targets: 147,
    receptions: 83,
    recYards: 1103,
    recTds: 4,
    fumbles: 1,
    teamName: "NYJ",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "T.J. Hockenson",
    adp: 42,
    position: "TE",
    totalPoints: 215.4,
    pointsPerGame: 12.7,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 0,
    rushYards: 0,
    rushTds: 0,
    targets: 129,
    receptions: 86,
    recYards: 914,
    recTds: 6,
    fumbles: 1,
    teamName: "MIN",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Alvin Kamara",
    adp: 57,
    position: "RB",
    totalPoints: 211.8,
    pointsPerGame: 14.1,
    gamesPlayed: 15,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 223,
    rushYards: 898,
    rushTds: 2,
    targets: 77,
    receptions: 57,
    recYards: 490,
    recTds: 2,
    fumbles: 4,
    teamName: "NO",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Travis Etienne Jr.",
    adp: 31,
    position: "RB",
    totalPoints: 205.1,
    pointsPerGame: 12.1,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 220,
    rushYards: 1125,
    rushTds: 5,
    targets: 45,
    receptions: 35,
    recYards: 316,
    recTds: 0,
    fumbles: 3,
    teamName: "JAX",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Jerry Jeudy",
    adp: 53,
    position: "WR",
    totalPoints: 204.2,
    pointsPerGame: 13.6,
    gamesPlayed: 15,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 4,
    rushYards: 40,
    rushTds: 0,
    targets: 100,
    receptions: 67,
    recYards: 972,
    recTds: 6,
    fumbles: 0,
    teamName: "DEN",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Kenneth Walker III",
    adp: 44,
    position: "RB",
    totalPoints: 202.6,
    pointsPerGame: 13.5,
    gamesPlayed: 15,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 228,
    rushYards: 1051,
    rushTds: 9,
    targets: 35,
    receptions: 27,
    recYards: 165,
    recTds: 0,
    fumbles: 0,
    teamName: "SEA",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Cooper Kupp",
    adp: 5,
    position: "WR",
    totalPoints: 201.4,
    pointsPerGame: 22.4,
    gamesPlayed: 9,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 9,
    rushYards: 52,
    rushTds: 1,
    targets: 98,
    receptions: 75,
    recYards: 812,
    recTds: 6,
    fumbles: 1,
    teamName: "LAR",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Kyler Murray",
    adp: 174,
    position: "QB",
    totalPoints: 200.5,
    pointsPerGame: 18.2,
    gamesPlayed: 11,
    completions: 259,
    passYards: 2368,
    passTds: 14,
    interceptions: 7,
    rushAttempts: 67,
    rushYards: 418,
    rushTds: 3,
    targets: 0,
    receptions: 0,
    recYards: 0,
    recTds: 0,
    fumbles: 2,
    teamName: "ARI",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "George Kittle",
    adp: 49,
    position: "TE",
    totalPoints: 200.5,
    pointsPerGame: 13.4,
    gamesPlayed: 15,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 0,
    rushYards: 0,
    rushTds: 0,
    targets: 86,
    receptions: 60,
    recYards: 765,
    recTds: 11,
    fumbles: 1,
    teamName: "SF",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "James Conner",
    adp: 62,
    position: "RB",
    totalPoints: 200.2,
    pointsPerGame: 15.4,
    gamesPlayed: 13,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 183,
    rushYards: 782,
    rushTds: 7,
    targets: 58,
    receptions: 46,
    recYards: 300,
    recTds: 1,
    fumbles: 1,
    teamName: "ARI",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "DJ Moore",
    adp: 52,
    position: "WR",
    totalPoints: 199.1,
    pointsPerGame: 11.7,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 10,
    rushYards: 53,
    rushTds: 0,
    targets: 118,
    receptions: 63,
    recYards: 888,
    recTds: 7,
    fumbles: 0,
    teamName: "CHI",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Dak Prescott",
    adp: 84,
    position: "QB",
    totalPoints: 198.6,
    pointsPerGame: 16.6,
    gamesPlayed: 12,
    completions: 261,
    passYards: 2860,
    passTds: 23,
    interceptions: 15,
    rushAttempts: 45,
    rushYards: 182,
    rushTds: 1,
    targets: 0,
    receptions: 0,
    recYards: 0,
    recTds: 0,
    fumbles: 1,
    teamName: "DAL",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Chris Olave",
    adp: 32,
    position: "WR",
    totalPoints: 198.2,
    pointsPerGame: 13.2,
    gamesPlayed: 15,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 0,
    rushYards: 0,
    rushTds: 0,
    targets: 119,
    receptions: 72,
    recYards: 1042,
    recTds: 4,
    fumbles: 2,
    teamName: "NO",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Zay Jones",
    adp: 166,
    position: "WR",
    totalPoints: 198.1,
    pointsPerGame: 12.4,
    gamesPlayed: 16,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 4,
    rushYards: 18,
    rushTds: 0,
    targets: 121,
    receptions: 82,
    recYards: 823,
    recTds: 5,
    fumbles: 0,
    teamName: "JAX",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Marcus Mariota",
    adp: 339,
    position: "QB",
    totalPoints: 196.6,
    pointsPerGame: 15.1,
    gamesPlayed: 13,
    completions: 184,
    passYards: 2219,
    passTds: 15,
    interceptions: 9,
    rushAttempts: 85,
    rushYards: 438,
    rushTds: 4,
    targets: 0,
    receptions: 0,
    recYards: 0,
    recTds: 0,
    fumbles: 3,
    teamName: "PHI",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Jerick McKinnon",
    adp: 118,
    position: "RB",
    totalPoints: 196.3,
    pointsPerGame: 11.5,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 72,
    rushYards: 291,
    rushTds: 1,
    targets: 71,
    receptions: 56,
    recYards: 512,
    recTds: 9,
    fumbles: 1,
    teamName: "KC",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "D'Andre Swift",
    adp: 69,
    position: "RB",
    totalPoints: 191.1,
    pointsPerGame: 13.7,
    gamesPlayed: 14,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 99,
    rushYards: 542,
    rushTds: 5,
    targets: 70,
    receptions: 48,
    recYards: 389,
    recTds: 3,
    fumbles: 0,
    teamName: "PHI",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Mark Andrews",
    adp: 26,
    position: "TE",
    totalPoints: 190.5,
    pointsPerGame: 12.7,
    gamesPlayed: 15,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 3,
    rushYards: 8,
    rushTds: 0,
    targets: 113,
    receptions: 73,
    recYards: 847,
    recTds: 5,
    fumbles: 0,
    teamName: "BAL",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Ezekiel Elliott",
    adp: 156,
    position: "RB",
    totalPoints: 185.8,
    pointsPerGame: 12.4,
    gamesPlayed: 15,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 231,
    rushYards: 876,
    rushTds: 12,
    targets: 23,
    receptions: 17,
    recYards: 92,
    recTds: 0,
    fumbles: 0,
    teamName: "NE",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "JuJu Smith-Schuster",
    adp: 100,
    position: "WR",
    totalPoints: 185.3,
    pointsPerGame: 11.6,
    gamesPlayed: 16,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 0,
    rushYards: 0,
    rushTds: 0,
    targets: 101,
    receptions: 78,
    recYards: 933,
    recTds: 3,
    fumbles: 2,
    teamName: "NE",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Davis Mills",
    adp: 1000,
    position: "QB",
    totalPoints: 181.5,
    pointsPerGame: 12.1,
    gamesPlayed: 15,
    completions: 292,
    passYards: 3118,
    passTds: 17,
    interceptions: 15,
    rushAttempts: 32,
    rushYards: 108,
    rushTds: 2,
    targets: 0,
    receptions: 0,
    recYards: 0,
    recTds: 0,
    fumbles: 3,
    teamName: "HOU",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Diontae Johnson",
    adp: 77,
    position: "WR",
    totalPoints: 180.7,
    pointsPerGame: 10.6,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 7,
    rushYards: 25,
    rushTds: 0,
    targets: 147,
    receptions: 86,
    recYards: 882,
    recTds: 0,
    fumbles: 0,
    teamName: "PIT",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Jakobi Meyers",
    adp: 140,
    position: "WR",
    totalPoints: 180.2,
    pointsPerGame: 12.9,
    gamesPlayed: 14,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 2,
    rushYards: -11,
    rushTds: 0,
    targets: 95,
    receptions: 67,
    recYards: 803,
    recTds: 6,
    fumbles: 2,
    teamName: "LV",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Adam Thielen",
    adp: 128,
    position: "WR",
    totalPoints: 180,
    pointsPerGame: 10.6,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 1,
    rushYards: 4,
    rushTds: 0,
    targets: 107,
    receptions: 70,
    recYards: 716,
    recTds: 6,
    fumbles: 0,
    teamName: "CAR",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Drake London",
    adp: 67,
    position: "WR",
    totalPoints: 178.6,
    pointsPerGame: 10.5,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 0,
    rushYards: 0,
    rushTds: 0,
    targets: 117,
    receptions: 72,
    recYards: 866,
    recTds: 4,
    fumbles: 3,
    teamName: "ATL",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Devin Singletary",
    adp: 148,
    position: "RB",
    totalPoints: 177.9,
    pointsPerGame: 11.1,
    gamesPlayed: 16,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 177,
    rushYards: 819,
    rushTds: 5,
    targets: 53,
    receptions: 38,
    recYards: 280,
    recTds: 1,
    fumbles: 3,
    teamName: "HOU",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "David Montgomery",
    adp: 83,
    position: "RB",
    totalPoints: 177.7,
    pointsPerGame: 11.1,
    gamesPlayed: 16,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 201,
    rushYards: 801,
    rushTds: 5,
    targets: 40,
    receptions: 34,
    recYards: 316,
    recTds: 1,
    fumbles: 2,
    teamName: "DET",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Evan Engram",
    adp: 78,
    position: "TE",
    totalPoints: 176.9,
    pointsPerGame: 10.4,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 2,
    rushYards: 13,
    rushTds: 0,
    targets: 98,
    receptions: 73,
    recYards: 766,
    recTds: 4,
    fumbles: 0,
    teamName: "JAX",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Mike Williams",
    adp: 61,
    position: "WR",
    totalPoints: 176.5,
    pointsPerGame: 13.6,
    gamesPlayed: 13,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 0,
    rushYards: 0,
    rushTds: 0,
    targets: 93,
    receptions: 63,
    recYards: 895,
    recTds: 4,
    fumbles: 0,
    teamName: "LAC",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Curtis Samuel",
    adp: 225,
    position: "WR",
    totalPoints: 176.3,
    pointsPerGame: 10.4,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 38,
    rushYards: 187,
    rushTds: 1,
    targets: 92,
    receptions: 64,
    recYards: 656,
    recTds: 4,
    fumbles: 1,
    teamName: "WAS",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Allen Lazard",
    adp: 131,
    position: "WR",
    totalPoints: 174.8,
    pointsPerGame: 11.7,
    gamesPlayed: 15,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 2,
    rushYards: 0,
    rushTds: 0,
    targets: 100,
    receptions: 60,
    recYards: 788,
    recTds: 6,
    fumbles: 0,
    teamName: "NYJ",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Andy Dalton",
    adp: 464,
    position: "QB",
    totalPoints: 174.2,
    pointsPerGame: 12.4,
    gamesPlayed: 14,
    completions: 252,
    passYards: 2870,
    passTds: 18,
    interceptions: 9,
    rushAttempts: 30,
    rushYards: 54,
    rushTds: 0,
    targets: 0,
    receptions: 0,
    recYards: 0,
    recTds: 0,
    fumbles: 1,
    teamName: "CAR",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Gabe Davis",
    adp: 103,
    position: "WR",
    totalPoints: 171.6,
    pointsPerGame: 11.4,
    gamesPlayed: 15,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 0,
    rushYards: 0,
    rushTds: 0,
    targets: 92,
    receptions: 48,
    recYards: 836,
    recTds: 7,
    fumbles: 1,
    teamName: "BUF",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Mac Jones",
    adp: 224,
    position: "QB",
    totalPoints: 170,
    pointsPerGame: 12.1,
    gamesPlayed: 14,
    completions: 288,
    passYards: 2996,
    passTds: 14,
    interceptions: 11,
    rushAttempts: 47,
    rushYards: 102,
    rushTds: 1,
    targets: 0,
    receptions: 0,
    recYards: 0,
    recTds: 0,
    fumbles: 1,
    teamName: "NE",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Joshua Palmer",
    adp: 299,
    position: "WR",
    totalPoints: 169.3,
    pointsPerGame: 10.6,
    gamesPlayed: 16,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 1,
    rushYards: 4,
    rushTds: 0,
    targets: 107,
    receptions: 72,
    recYards: 769,
    recTds: 3,
    fumbles: 0,
    teamName: "LAC",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Jacoby Brissett",
    adp: 1000,
    position: "QB",
    totalPoints: 168.6,
    pointsPerGame: 10.5,
    gamesPlayed: 16,
    completions: 236,
    passYards: 2608,
    passTds: 12,
    interceptions: 6,
    rushAttempts: 49,
    rushYards: 243,
    rushTds: 2,
    targets: 0,
    receptions: 0,
    recYards: 0,
    recTds: 0,
    fumbles: 4,
    teamName: "CLE",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Deebo Samuel",
    adp: 38,
    position: "WR",
    totalPoints: 168.4,
    pointsPerGame: 13,
    gamesPlayed: 13,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 42,
    rushYards: 232,
    rushTds: 3,
    targets: 94,
    receptions: 56,
    recYards: 632,
    recTds: 2,
    fumbles: 2,
    teamName: "SF",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Raheem Mostert",
    adp: 150,
    position: "RB",
    totalPoints: 168.3,
    pointsPerGame: 10.5,
    gamesPlayed: 16,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 181,
    rushYards: 891,
    rushTds: 3,
    targets: 42,
    receptions: 31,
    recYards: 202,
    recTds: 2,
    fumbles: 1,
    teamName: "MIA",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "AJ Dillon",
    adp: 88,
    position: "RB",
    totalPoints: 167.6,
    pointsPerGame: 9.9,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 186,
    rushYards: 770,
    rushTds: 7,
    targets: 43,
    receptions: 28,
    recYards: 206,
    recTds: 0,
    fumbles: 0,
    teamName: "GB",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "George Pickens",
    adp: 85,
    position: "WR",
    totalPoints: 166.5,
    pointsPerGame: 9.8,
    gamesPlayed: 17,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 3,
    rushYards: 24,
    rushTds: 1,
    targets: 85,
    receptions: 52,
    recYards: 801,
    recTds: 4,
    fumbles: 0,
    teamName: "PIT",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Dameon Pierce",
    adp: 48,
    position: "RB",
    totalPoints: 166.4,
    pointsPerGame: 12.8,
    gamesPlayed: 13,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 220,
    rushYards: 939,
    rushTds: 4,
    targets: 39,
    receptions: 30,
    recYards: 165,
    recTds: 1,
    fumbles: 2,
    teamName: "HOU",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Tyler Boyd",
    adp: 147,
    position: "WR",
    totalPoints: 166.2,
    pointsPerGame: 10.4,
    gamesPlayed: 16,
    completions: 1,
    passYards: 23,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 0,
    rushYards: 0,
    rushTds: 0,
    targets: 82,
    receptions: 58,
    recYards: 762,
    recTds: 5,
    fumbles: 0,
    teamName: "CIN",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Antonio Gibson",
    adp: 108,
    position: "RB",
    totalPoints: 165.9,
    pointsPerGame: 11.1,
    gamesPlayed: 15,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 149,
    rushYards: 546,
    rushTds: 3,
    targets: 58,
    receptions: 46,
    recYards: 353,
    recTds: 2,
    fumbles: 0,
    teamName: "WAS",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Jimmy Garoppolo",
    adp: 217,
    position: "QB",
    totalPoints: 164.8,
    pointsPerGame: 15,
    gamesPlayed: 11,
    completions: 207,
    passYards: 2437,
    passTds: 16,
    interceptions: 4,
    rushAttempts: 23,
    rushYards: 33,
    rushTds: 2,
    targets: 0,
    receptions: 0,
    recYards: 0,
    recTds: 0,
    fumbles: 2,
    teamName: "LV",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Christian Watson",
    adp: 55,
    position: "WR",
    totalPoints: 164.1,
    pointsPerGame: 11.7,
    gamesPlayed: 14,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 7,
    rushYards: 80,
    rushTds: 2,
    targets: 65,
    receptions: 41,
    recYards: 611,
    recTds: 7,
    fumbles: 0,
    teamName: "GB",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Keenan Allen",
    adp: 43,
    position: "WR",
    totalPoints: 164,
    pointsPerGame: 16.4,
    gamesPlayed: 10,
    completions: 0,
    passYards: 0,
    passTds: 0,
    interceptions: 0,
    rushAttempts: 1,
    rushYards: 8,
    rushTds: 0,
    targets: 89,
    receptions: 66,
    recYards: 752,
    recTds: 4,
    fumbles: 1,
    teamName: "LAC",
  },
  {
    id: 1,
    wishlist: false,
    price: 1,
    name: "Ryan Tannehill",
    adp: 245,
    position: "QB",
    totalPoints: 161.2,
    pointsPerGame: 13.4,
    gamesPlayed: 12,
    completions: 212,
    passYards: 2536,
    passTds: 13,
    interceptions: 6,
    rushAttempts: 34,
    rushYards: 98,
    rushTds: 2,
    targets: 0,
    receptions: 0,
    recYards: 0,
    recTds: 0,
    fumbles: 2,
    teamName: "TEN",
  },
];
